export const columnsXstj = [
  {
    label: '款号',
    prop: 'kh',
    width: 100,
    show: true
  }, {
    label: '日期',
    prop: 'rq',
    width: 100,
    show: true
  }, {
    label: '类型',
    prop: 'lx',
    width: 100,
    show: true
  }, {
    label: '客户',
    prop: 'khmc',
    width: 100,
    show: true
  }, {
    label: '仓库',
    prop: 'ckmc',
    width: 100,
    show: true
  }, {
    label: '商标',
    prop: 'sb',
    width: 100,
    show: true
  }, {
    label: '数量',
    prop: 'sl',
    sumProp: 'sl',
    width: 100,
    show: true
  }, {
    label: '单位',
    prop: 'dw',
    width: 100,
    show: true
  }, {
    label: '单价',
    prop: 'dj',
    width: 100,
    show: true
  }, {
    label: '金额',
    prop: 'je',
    sumProp: 'je',
    width: 100,
    show: true
  }, {
    label: '引用单号',
    prop: 'yydh',
    width: 100,
    show: true
  }, {
    label: '备注',
    prop: 'bz',
    width: 100,
    show: true
  }, {
    label: '不减库存',
    prop: 'sfkc',
    width: 100,
    show: true,
    elType: 'checkbox',
    align: 'center',
    disabled: true
  }
]
export const columnsRktj = [
  {
    label: '款号',
    prop: 'kh',
    width: 100,
    show: true
  }, {
    label: '日期',
    prop: 'rq',
    width: 100,
    show: true
  }, {
    label: '类型',
    prop: 'lx',
    width: 100,
    show: true
  }, {
    label: '供货商名称',
    prop: 'ghsmc',
    width: 100,
    show: true
  }, {
    label: '仓库',
    prop: 'ckmc',
    width: 100,
    show: true
  }, {
    label: '商标',
    prop: 'sb',
    width: 100,
    show: true
  }, {
    label: '数量',
    prop: 'sl',
    sumProp: 'sl',
    width: 100,
    show: true
  }, {
    label: '单位',
    prop: 'dw',
    width: 100,
    show: true
  }, {
    label: '单价',
    prop: 'dj',
    width: 100,
    show: true
  }, {
    label: '金额',
    prop: 'je',
    sumProp: 'je',
    width: 100,
    show: true
  }, {
    label: '引用单号',
    prop: 'yydh',
    width: 100,
    show: true
  }, {
    label: '备注',
    prop: 'bz',
    width: 100,
    show: true
  }
]
export const columnsPdtj = [
  {
    label: '款号',
    prop: 'kh',
    width: 100,
    show: true
  }, {
    label: '日期',
    prop: 'rq',
    width: 100,
    show: true
  }, {
    label: '类型',
    prop: 'lx',
    width: 100,
    show: true
  }, {
    label: '仓库',
    prop: 'ckmc',
    width: 100,
    show: true
  }, {
    label: '商标',
    prop: 'sb',
    width: 100,
    show: true
  }, {
    label: '数量',
    prop: 'sl',
    sumProp: 'sl',
    width: 100,
    show: true
  }, {
    label: '单位',
    prop: 'dw',
    width: 100,
    show: true
  }, {
    label: '备注',
    prop: 'bz',
    width: 100,
    show: true
  }
]
