export const columnsKh = [
  {
    label: '客户名称',
    prop: 'khmc',
    width: 100,
    show: true
  },
  {
    label: '客户类型',
    prop: 'lx',
    width: 100,
    show: true
  }, {
    label: '上次结欠',
    prop: 'qqje',
    width: 100,
    show: true,
    sumProp: 'qqje'
  }, {
    label: '销售额',
    prop: 'xsje',
    width: 100,
    show: true,
    sumProp: 'xsje'
  }, {
    label: '付款额',
    prop: 'fkje',
    width: 100,
    show: true,
    sumProp: 'fkje'
  }, {
    label: '收款额',
    prop: 'skje',
    width: 100,
    show: true,
    sumProp: 'skje'
  }, {
    label: '退款额',
    prop: 'tkje',
    width: 100,
    show: true,
    sumProp: 'tkje'
  }, {
    label: '业务调账额',
    prop: 'tzje',
    width: 100,
    show: true,
    sumProp: 'tzje'
  }, {
    label: '其他金额',
    prop: 'qtje',
    width: 100,
    show: true,
    sumProp: 'qtje'
  }, {
    label: '本次结欠',
    prop: 'ljqk',
    width: 100,
    show: true,
    sumProp: 'ljqk'
  }, {
    label: '当前累欠',
    prop: 'templjqk',
    width: 100,
    show: true,
    sumProp: 'templjqk'
  }, {
    label: '客户顺序',
    prop: 'khsx',
    width: 100,
    show: true
  }
]
export const columnsGhs = [
  {
    label: '供货商',
    prop: 'khmc',
    width: 100,
    show: true
  }, {
    label: '上次结欠',
    prop: 'qqje',
    width: 100,
    show: true,
    sumProp: 'qqje'
  }, {
    label: '采购额',
    prop: 'xsje',
    width: 100,
    show: true,
    sumProp: 'xsje'
  }, {
    label: '付款额',
    prop: 'fkje',
    width: 100,
    show: true,
    sumProp: 'fkje'
  }, {
    label: '收款额',
    prop: 'skje',
    width: 100,
    show: true,
    sumProp: 'skje'
  }, {
    label: '退款额',
    prop: 'tkje',
    width: 100,
    show: true,
    sumProp: 'tkje'
  }, {
    label: '业务调账额',
    prop: 'tzje',
    width: 100,
    show: true,
    sumProp: 'tzje'
  }, {
    label: '其他金额',
    prop: 'qtje',
    width: 100,
    show: true,
    sumProp: 'qtje'
  }, {
    label: '本次结欠',
    prop: 'ljqk',
    width: 100,
    show: true,
    sumProp: 'ljqk'
  }, {
    label: '当前累欠',
    prop: 'templjqk',
    width: 100,
    show: true,
    sumProp: 'templjqk'
  }
]
export const columnsJgs = [
  {
    label: '加工商',
    prop: 'khmc',
    width: 100,
    show: true
  }, {
    label: '上次结欠',
    prop: 'qqje',
    width: 100,
    show: true,
    sumProp: 'qqje'
  }, {
    label: '加工额',
    prop: 'xsje',
    width: 100,
    show: true,
    sumProp: 'xsje'
  }, {
    label: '付款额',
    prop: 'fkje',
    width: 100,
    show: true,
    sumProp: 'fkje'
  }, {
    label: '收款额',
    prop: 'skje',
    width: 100,
    show: true,
    sumProp: 'skje'
  }, /* {
    label: '销售额',
    prop: 'xsje',
    width: 100,
    show: true,
    sumProp: 'xsje'
  }, */ {
    label: '业务调账额',
    prop: 'tzje',
    width: 100,
    show: true,
    sumProp: 'tzje'
  }, {
    label: '其他金额',
    prop: 'qtje',
    width: 100,
    show: true,
    sumProp: 'qtje'
  }, {
    label: '本次结欠',
    prop: 'ljqk',
    width: 100,
    show: true,
    sumProp: 'ljqk'
  }, {
    label: '当前累欠',
    prop: 'templjqk',
    width: 100,
    show: true,
    sumProp: 'templjqk'
  }
]
