export const columnsKh = [
  {
    label: '客户名称',
    prop: 'khmc',
    width: 100,
    show: true
  },
  {
    label: '客户类型',
    prop: 'khlx',
    width: 100,
    show: true
  }, {
    label: '上次结欠',
    prop: 'scjq',
    width: 100,
    show: true,
    sumProp: 'scjq'
  }, {
    label: '销售额',
    prop: 'xse',
    width: 100,
    show: true,
    sumProp: 'xse'
  }, {
    label: '付款额',
    prop: 'fke',
    width: 100,
    show: true,
    sumProp: 'fke'
  }, {
    label: '收款额',
    prop: 'ske',
    width: 100,
    show: true,
    sumProp: 'ske'
  }, {
    label: '退款额',
    prop: 'tke',
    width: 100,
    show: true,
    sumProp: 'tke'
  }, {
    label: '业务调账额',
    prop: 'ywtze',
    width: 100,
    show: true,
    sumProp: 'ywtze'
  }, {
    label: '其他金额',
    prop: 'qtje',
    width: 100,
    show: true,
    sumProp: 'qtje'
  }, {
    label: '本次结欠',
    prop: 'bcjq',
    width: 100,
    show: true,
    sumProp: 'bcjq'
  }, {
    label: '当前累欠',
    prop: 'dqlq',
    width: 100,
    show: true,
    sumProp: 'dqlq'
  }, {
    label: '客户顺序',
    prop: 'khsx',
    width: 100,
    show: true
  }
]
export const columnsGhs = [
  {
    label: '供货商',
    prop: 'ghs',
    width: 100,
    show: true
  }, {
    label: '上次结欠',
    prop: 'scjq',
    width: 100,
    show: true,
    sumProp: 'scjq'
  }, {
    label: '采购额',
    prop: 'cge',
    width: 100,
    show: true,
    sumProp: 'cge'
  }, {
    label: '付款额',
    prop: 'fke',
    width: 100,
    show: true,
    sumProp: 'fke'
  }, {
    label: '收款额',
    prop: 'ske',
    width: 100,
    show: true,
    sumProp: 'ske'
  }, {
    label: '退款额',
    prop: 'tke',
    width: 100,
    show: true,
    sumProp: 'tke'
  }, {
    label: '业务调账额',
    prop: 'ywtze',
    width: 100,
    show: true,
    sumProp: 'ywtze'
  }, {
    label: '其他金额',
    prop: 'qtje',
    width: 100,
    show: true,
    sumProp: 'qtje'
  }, {
    label: '本次结欠',
    prop: 'bcjq',
    width: 100,
    show: true,
    sumProp: 'bcjq'
  }, {
    label: '当前累欠',
    prop: 'dqlq',
    width: 100,
    show: true,
    sumProp: 'dqlq'
  }
]
export const columnsJgs = [
  {
    label: '加工商',
    prop: 'jgs',
    width: 100,
    show: true
  }, {
    label: '上次结欠',
    prop: 'scjq',
    width: 100,
    show: true,
    sumProp: 'scjq'
  }, {
    label: '加工额',
    prop: 'jge',
    width: 100,
    show: true,
    sumProp: 'cge'
  }, {
    label: '付款额',
    prop: 'fke',
    width: 100,
    show: true,
    sumProp: 'fke'
  }, {
    label: '收款额',
    prop: 'ske',
    width: 100,
    show: true,
    sumProp: 'ske'
  }, {
    label: '销售额',
    prop: 'xse',
    width: 100,
    show: true,
    sumProp: 'xse'
  }, {
    label: '业务调账额',
    prop: 'ywtze',
    width: 100,
    show: true,
    sumProp: 'ywtze'
  }, {
    label: '其他金额',
    prop: 'qtje',
    width: 100,
    show: true,
    sumProp: 'qtje'
  }, {
    label: '本次结欠',
    prop: 'bcjq',
    width: 100,
    show: true,
    sumProp: 'bcjq'
  }, {
    label: '当前累欠',
    prop: 'dqlq',
    width: 100,
    show: true,
    sumProp: 'dqlq'
  }
]
