export const columnsCkdwmx = [
  {
    label: '档位',
    prop: 'kw',
    width: 100,
    show: true
  }, {
    label: '档位商标',
    prop: 'dwsb',
    width: 100,
    show: true
  }, {
    label: '档位款式类型',
    prop: 'dwkslx',
    width: 100,
    show: true
  }, {
    label: '档位类型',
    prop: 'dwlx',
    width: 100,
    show: true
  }, {
    label: '是否关联类型',
    prop: 'sfgllx',
    width: 100,
    show: true,
    elType: 'checkbox',
    align: 'center'
  }, {
    label: '档位容量',
    prop: 'dwrl',
    width: 100,
    show: true
  }, {
    label: '尺码档位',
    prop: 'cmdw',
    width: 100,
    show: true
  }, {
    label: '剩余容量',
    prop: 'syrl',
    width: 100,
    show: true
  }, {
    label: '已用容量',
    prop: 'yyrl',
    width: 100,
    show: true
  }, {
    label: '商标',
    prop: 'sb',
    width: 100,
    show: true
  }, {
    label: '款号',
    prop: 'kh',
    width: 100,
    show: true
  }, {
    label: '码数',
    prop: 'ms',
    width: 100,
    show: true
  }, {
    label: '款式类型',
    prop: 'kslx',
    width: 100,
    show: true
  }, {
    label: '单位',
    prop: 'dw',
    width: 100,
    show: true
  }, {
    label: '颜色',
    prop: 'ys',
    width: 100,
    show: true
  }, {
    label: '数量',
    prop: 'sl',
    sumProp: 'sl',
    width: 100,
    show: true
  }, {
    label: '备注',
    prop: 'bz',
    width: 100,
    show: true
  }
]
export const columnsCkdwhz = [
  {
    label: '仓库档位',
    prop: 'kw',
    width: 100,
    show: true
  }, {
    label: '档位商标',
    prop: 'dwsb',
    width: 100,
    show: true
  }, {
    label: '档位款式类型',
    prop: 'dwkslx',
    width: 100,
    show: true
  }, {
    label: '档位类型',
    prop: 'dwlx',
    width: 100,
    show: true
  }, {
    label: '是否关联类型',
    prop: 'sfgllx',
    width: 100,
    show: true,
    elType: 'checkbox',
    align: 'center',
    disabled: true
  }, {
    label: '档位容量',
    prop: 'rl',
    width: 100,
    show: true
  }, {
    label: '尺码档位',
    prop: 'cm',
    width: 100,
    show: true
  }, {
    label: '剩余容量',
    prop: 'kyrl',
    width: 100,
    show: true
  }, {
    label: '已用容量',
    prop: 'yyrl',
    width: 100,
    show: true
  }, {
    label: '是否预留',
    prop: 'sfyl',
    width: 100,
    show: true,
    elType: 'checkbox',
    align: 'center',
    disabled: true
  }
]
