export const columnsDetail = [
  {
    label: '日期',
    prop: 'jhrq',
    width: 136,
    show: true,
    elType: 'date'
  }, {
    label: '员工简码',
    prop: 'ygjm',
    width: 100,
    show: true,
    sendKey: 'jm',
    elType: 'autocomplete',
    api: 'getStaff',
    relation: ['yggh', 'ygmc']
  }, {
    label: '员工工号',
    prop: 'yggh',
    width: 100,
    show: true,
    elType: 'autocomplete',
    api: 'getStaff',
    relation: ['jm->ygjm', 'ygmc']
  }, {
    label: '员工名称',
    prop: 'ygmc',
    width: 100,
    show: true,
    elType: 'autocomplete',
    api: 'getStaff',
    relation: ['yggh', 'jm->ygjm']
  }, {
    label: '床号',
    prop: 'ch',
    width: 100,
    show: true,
    elType: 'autocomplete',
    api: 'getBedNum2',
    relation: ['zdch']
  }, {
    label: '自动床号',
    prop: 'zdch',
    width: 100,
    show: true,
    elType: 'autocomplete',
    api: 'getBedNum2',
    relation: ['ch']
  }, {
    label: '商标',
    prop: 'sb',
    width: 100,
    show: true,
    elType: 'autocomplete',
    api: 'getTrademark'
  }, {
    label: '款号',
    prop: 'kh',
    width: 100,
    show: true,
    elType: 'autocomplete',
    api: 'getProductionRegisterFashion',
    superKeys: ['ch'],
    relation: ['kslx', 'dw']
  }, {
    label: '款式类型',
    prop: 'kslx',
    width: 100,
    show: true,
    readonly: true
  }, {
    label: '工序简码',
    prop: 'gxjm',
    width: 100,
    show: true,
    readonly: true
  }, {
    label: '工序名称',
    prop: 'gxmc',
    width: 100,
    show: true,
    elType: 'autocomplete',
    api: 'getFashionProcess',
    superKeys: ['kh'],
    autocompleteFn: true,
    relation: ['jm->gxjm', 'gj->dj']
  }, {
    label: '码数',
    prop: 'ms',
    width: 100,
    show: true,
    elType: 'autocomplete',
    api: 'getFashionSize',
    superKeys: ['kh']
  }, {
    label: '入库',
    prop: 'sfrk',
    width: 100,
    show: true,
    elType: 'checkbox',
    align: 'center'
  }, {
    label: '颜色',
    prop: 'ysmc',
    width: 100,
    show: true,
    elType: 'autocomplete',
    api: 'getFashionColor',
    superKeys: ['kh']
  }, {
    label: '工价',
    prop: 'dj',
    width: 100,
    show: true
  }, {
    label: '数量',
    prop: 'jhsl',
    width: 100,
    show: true
  }, {
    label: '单位',
    prop: 'dw',
    width: 100,
    show: true
  }, {
    label: '金额',
    prop: 'je',
    width: 100,
    show: true,
    computed: `
      return this.$math.multiply(parseFloat(r.jhsl || 0), parseFloat(r.dj || 0))
    `,
    readonly: true
  }, {
    label: '备注',
    prop: 'bz',
    width: 100,
    show: true
  }, {
    label: '制单人',
    prop: 'zdr',
    width: 100,
    show: true,
    readonly: true,
    defaultVal: () => {
      return JSON.parse(localStorage.getItem('account')).username
    }
  }
]
export const columnsList = [
  {
    label: '领货日期',
    prop: 'rq',
    width: 100,
    show: true
  }, {
    label: '员工工号',
    prop: 'yggh',
    width: 100,
    show: true
  }, {
    label: '员工名称',
    prop: 'ygmc',
    width: 100,
    show: true
  }, {
    label: '款号',
    prop: 'kh',
    width: 100,
    show: true
  }, {
    label: '款式类型',
    prop: 'kslx',
    width: 100,
    show: true
  }, {
    label: '工序名称',
    prop: 'gxmc',
    width: 100,
    show: true
  }, {
    label: '颜色',
    prop: 'ysmc',
    width: 100,
    show: true
  }, {
    label: '码数',
    prop: 'ms',
    width: 100,
    show: true
  }, {
    label: '领货数量',
    prop: 'sl',
    width: 100,
    show: true
  }, {
    label: '工价',
    prop: 'dj',
    width: 100,
    show: true
  }, {
    label: '交货日期',
    prop: 'jhrq',
    width: 100,
    show: true
  }, {
    label: '交货数量',
    prop: 'jhsl',
    width: 100,
    show: true
  }, {
    label: '金额',
    prop: 'je',
    width: 100,
    show: true
  }, {
    label: '备注',
    prop: 'bz',
    width: 100,
    show: true
  }, {
    label: '结算',
    prop: 'zt',
    width: 100,
    elType: 'checkbox',
    align: 'center',
    disabled: true,
    show: true
  }, {
    label: '床号',
    prop: 'ch',
    width: 100,
    show: true
  }, {
    label: '自动床号',
    prop: 'zdch',
    width: 100,
    show: true
  }, {
    label: '磁卡编号',
    prop: 'tmbh',
    width: 100,
    show: true
  }, {
    label: '拆解工票码',
    prop: 'cjgpm',
    width: 100,
    show: true
  }, {
    label: '入库',
    prop: 'sfrk',
    width: 100,
    elType: 'checkbox',
    align: 'center',
    show: true,
    disabled: true
  }, {
    label: '商标',
    prop: 'sb',
    width: 100,
    show: true
  }, {
    label: '制单人',
    prop: 'zdr',
    width: 100,
    show: true
  }
]
